### ISSUE TITLE
Synchronize Carbon locale with Laravel locale

### ISSUE THREAD

**Issue by Nuranto** [kylekatarnls/laravel-carbon-2#1]
```
 {{ app()->getLocale() }}  // displays 'fr'
$anyCarbon2Date->locale() // displays 'en'
```

App config is : 
```
'locale' => 'fr',
```

**Comment by kylekatarnls** [comment]
Hi, I use a middleware for this and get no trouble `->locale()` outputs `fr` and yesterday display *Hier* can you try `app()->setLocale('fr')` to check the update?

**Comment by kylekatarnls** [comment]
Oh, I forgot which version of Laravel do you use? Because this feature uses auto-discovery (added in Laravel 5.5), if older, you need to add manually `Carbon\Laravel\ServiceProvider` to your providers.

**Comment by Nuranto** [comment]
Hello,

I'm using Laravel 5.6.
I had to manually add `Carbon::setLocale(app()->getLocale());` in AppServiceProvider, and it works fine now.

But you're right, I just checked, and indeed, I disabled auto discovery... So, I will use provider instead of  the above solution! Thanks.

**Comment by kylekatarnls** [comment]
Great, the point is: Carbon is NOT a Laravel library, it's a PHP date library you can use with Laravel or with any other PHP app/framework. So it won't get automatically the Laravel locale until you load the `Carbon\Laravel\ServiceProvider` either manually or via auto-discovery.

Thanks.

**Comment by Nuranto** [comment]
Yes my bad, I just forgot I disabled auto discovery! Sorry about that... :)
Anyway, thanks for you help!
