### ISSUE TITLE
Compatible Lumen 5.6

### ISSUE THREAD

**Issue by innovaweb-dev** [kylekatarnls/laravel-carbon-2#2]
Hi everyone and thanks for your help.

Is it compatible with Lumen 5.6.* ?
If yes, which anyone can say me how to install  and to use its ?
Thanks again,

**Comment by kylekatarnls** [comment]
Hi, basically Carbon can be used with any PHP app/framework. And if there is no conflict with Laravel, so it goes for Lumen.

You should already have Carbon installed as it's required by illuminate/support (required by Lumen framework).

But you still can install it in any place with `composer require nesbot/carbon`, and to use the different classes, just add the `use` statements at the top of the files for the classes you need:

```php
<?php

use Carbon\Carbon;
use Carbon\CarbonImmutable;
use Carbon\CarbonInterval;
use Carbon\CarbonPeriod;
```

I guess if you use Eloquent, you will have Carbon for dates in your models.

**Comment by innovaweb-dev** [comment]
It's okay for me.
Thanks @kylekatarnls
```
    "require": {
        "php": ">=7.1.3",
        "laravel/lumen-framework": "5.6.*",
        "vlucas/phpdotenv": "~2.2",
        "illuminate/mail": "5.6.*",
        "kylekatarnls/laravel-carbon-2": "^1.0.0",
        "nesbot/carbon": "2.8.0 as 1.25.0"
    },
```
